spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: h2test
    password: ENC(Ghav43hc9yFhkvY4fQsjpA==)

  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /szs/**

security:
  secretKey: ENC(vvPQi/GguO8LHFEabTCiVAGOnhdb8g7r)
  session.expire: 10h
